// Module2_FrontendDev/hands_on_08/student-portal-vue/src/App.vue
<template>
  <header class="app-header">
    <span class="logo">🎓 Student Portal (Vue)</span>
    <nav>
      <RouterLink to="/">Courses</RouterLink>
      <RouterLink to="/profile">
        Profile
        <span class="badge">{{ store.enrolledCourses.length }}</span>
      </RouterLink>
    </nav>
  </header>

  <RouterView />

  <footer class="app-footer">&copy; 2024 Student Portal — Vue.js</footer>
</template>

<script setup>
import { useEnrollmentStore } from '@/stores/enrollment';
const store = useEnrollmentStore();
</script>

<style>
* { margin:0; padding:0; box-sizing:border-box; }
body { font-family:Arial,sans-serif; background:#f4f6f9; }
.app-header { background:#1a73e8; color:white; padding:16px 32px; display:flex; justify-content:space-between; align-items:center; }
.logo { font-size:1.3rem; font-weight:bold; }
nav { display:flex; gap:20px; align-items:center; }
nav a { color:white; text-decoration:none; }
.badge { background:white; color:#1a73e8; border-radius:20px; padding:2px 10px; font-size:0.8rem; font-weight:bold; margin-left:6px; }
.app-footer { background:#1a73e8; color:white; text-align:center; padding:16px; margin-top:40px; }
</style>

// Module2_FrontendDev/hands_on_06/student-portal-routing/src/App.jsx
import { BrowserRouter, Routes, Route, Link } from 'react-router-dom';
import { useSelector } from 'react-redux';
import HomePage       from './pages/HomePage';
import CoursesPage    from './pages/CoursesPage';
import CourseDetailPage from './pages/CourseDetailPage';
import ProfilePage    from './pages/ProfilePage';

function App() {
  const enrolledCount = useSelector(state => state.enrollment.enrolledCourses.length);

  return (
    <BrowserRouter>
      <header style={{ background:'#1a73e8', color:'white', padding:'16px 32px', display:'flex', justifyContent:'space-between', alignItems:'center' }}>
        <div style={{ fontWeight:'bold', fontSize:'1.3rem' }}>🎓 Student Portal</div>
        <nav style={{ display:'flex', gap:'20px', alignItems:'center' }}>
          <Link to="/"        style={{ color:'white', textDecoration:'none' }}>Home</Link>
          <Link to="/courses" style={{ color:'white', textDecoration:'none' }}>Courses</Link>
          <Link to="/profile" style={{ color:'white', textDecoration:'none' }}>Profile</Link>
          <span style={{ background:'white', color:'#1a73e8', borderRadius:'20px', padding:'4px 12px', fontWeight:'bold', fontSize:'0.85rem' }}>
            Enrolled: {enrolledCount}
          </span>
        </nav>
      </header>

      <main style={{ minHeight:'80vh' }}>
        <Routes>
          <Route path="/"               element={<HomePage />}         />
          <Route path="/courses"        element={<CoursesPage />}      />
          <Route path="/courses/:courseId" element={<CourseDetailPage />} />
          <Route path="/profile"        element={<ProfilePage />}      />
        </Routes>
      </main>

      <footer style={{ background:'#1a73e8', color:'white', textAlign:'center', padding:'16px' }}>
        &copy; 2024 Student Portal
      </footer>
    </BrowserRouter>
  );
}

export default App;
